/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_2;

import java.util.Scanner;

public class App {
    
   public static void main(String[] args) {
      
        float centigrados,fahrenheit,kelvin;
        Scanner obxScaner= new Scanner (System.in);
        System.out.println("Teclea centigrados");
        centigrados= obxScaner.nextFloat();
        
        fahrenheit= (centigrados*9/5)+32;
        kelvin= (float) (centigrados+273.15);
        
        System.out.println(centigrados + " grados centigrados son "+ fahrenheit + " grados Fahrenheit y son " + kelvin + " grados Kelvin");
        
    }
}
