/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_1;

import java.util.Scanner;

public class App {
    
     public static void main(String[] args) {
        
           float Ptarifa, Ppagado, descuento;
           Scanner obxScaner = new Scanner (System.in);
           System.out.println("Teclea Ptarifa");
           Ptarifa= obxScaner.nextFloat();
           System.out.println("Teclea Ppagado");
           Ppagado= obxScaner.nextFloat();
           
           descuento= ((Ptarifa-Ppagado)/Ptarifa)*100;
           
           System.out.println("el descuento=" +descuento+"%");
    }
  }
