/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_3;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
       //System.out.println(new App().getGreeting());
        int numBilletes100, numBilletes20, numBilletes5, numMonedas1,euros;
        Scanner obxScaner= new Scanner (System.in);
        System.out.println("Teclea numero de billetes de 100");
        numBilletes100= obxScaner.nextInt();
        System.out.println("Teclea numero de billetes de 20");
        numBilletes20= obxScaner.nextInt();
        System.out.println("Teclea numero de billetes de 5");
        numBilletes5= obxScaner.nextInt();
        System.out.println("Teclea numero de monedas de 1");
        numMonedas1= obxScaner.nextInt();
        
        euros= (numBilletes100*100)+(numBilletes20*20)+(numBilletes5*5)+(numMonedas1*1);
        
        System.out.println("la cantidad total de euros es="+euros);
    }
}
